# Generated by Django 6.0 on 2025-12-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancy',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
