# Generated by Django 6.0 on 2025-12-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0002_alter_consultancy_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancy',
            name='email',
        ),
    ]
